version: "3.3"

services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    ports:
      - 3000:3000
    volumes:
      - ./config:/app/config # Make sure your local config directory exists
    env_file: .env
    environment:
      PUID: $PUID
      PGID: $PGID
    networks:
      - docker_network
    restart: unless-stopped

networks:
  docker_network:
    external: true
