- Infrastructure:
    - Portainer:
        icon: portainer.svg
        href: https://portainer.yumo4.duckdns.org
    - PiHole:
        icon: pi-hole.svg
        href: https://pihole.yumo4.duckdns.org
    - FritzBox:
        icon: avmfritzbox.svg
        href: fritz.box
    - Nginx-Proxy-Manager:
        icon: nginx-proxy-manager.svg
        href: https://proxy.yumo4.duckdns.org

- Services:
    - Syncthing:
        icon: syncthing.svg
        href: https://syncthing.yumo4.duckdns.org
    - Vaultwarden:
        icon: bitwarden.svg
        href: https://vaultwarden.yumo4.duckdns.org

