title: home-one dashboard
theme: dark
color: stone
# background:
#   image: https://cdnb.artstation.com/p/assets/images/images/066/876/365/large/benjamin-last-homeone-hangar-blast.jpg?1693994657
#   blur: sm
#   saturate: 70
#   brightness: 70
#   opacity: 50
