version: "3.8"

services:
  homer:
    image: b4bz/homer
    #To build from source, comment previous line and uncomment below
    #build: .
    container_name: homer
    volumes:
      - /home/home-one/docker/homer/:/www/assets
    ports:
      - 8181:8181
    user: 1000:1000 # default
    environment:
      - INIT_ASSETS=1 # default
    networks:
      - docker_network
    restart: unless-stopped

networks:
  docker_network:
    external: true
