version: '3.8'

services:
  portainer:
    container_name: portainer
    image: portainer/portainer-ce:latest
    ports:
      - '9443:9443'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./portainer_data:/data
    networks:
      - docker_network
    restart: unless-stopped

networks:
  docker_network:
    external: true
